Scridon Darius
speedy4all/pentastagiu-java-2019-2020 pull request #22
Opened 2019-12-09 10:47 UTC by ScridonDarius

First homework is done.

2019-12-09 13:17 UTC, cosmin-margarit commented on src/Homework2.java
> +                System.out.print(previousNumber + " ");
Seria lui fibonacci porneste de la 1

2019-12-09 13:45 UTC, cosmin-margarit requested changes

2019-12-09 13:45 UTC, cosmin-margarit commented on src/Homework2.java
> +            return "Given  the following array " + Arrays.toString(array) + " and a target element " + element + "  the output is : " + i + "\n(because " + element + " is located at index " + i + " i
Daca elementul tau nu se afla pr prima pozitia algoritmul asta o sa iti returneze intotdeauna 1 fiindca atunci cand ajungi la return iti iese din functie.

2019-12-09 13:45 UTC, cosmin-margarit commented on src/Homework2.java
> +        for (int i = 0; i <= array.length - 1; i++) {
De obicei nu scriem`≤ length-1`.  Daca pleci de la 0 folosesti mai mic stric `<`

2019-12-09 13:45 UTC, cosmin-margarit commented on src/Homework2.java
> +            int result = (array[i] % 2 == 0) ? odd++ : even++;
Foarte bine ca ai folosit operatorul ternar, insa ai inversat ramurile. `conditie ? adevar: fals`

2019-12-09 17:40 UTC, ScridonDarius commented on src/Homework2.java
> +                System.out.print(previousNumber + " ");
Depinde eu stiu ca de la 0 inclusiv asa e fibonacci

2019-12-09 17:44 UTC, ScridonDarius commented on src/Homework2.java
> +            int result = (array[i] % 2 == 0) ? odd++ : even++;
Da vazusem acum aseara pe la 3 le-am facut :D

2019-12-13 07:56 UTC, cosmin-margarit commented
Good job! 👍 

O sa inchid aceast PR pentru a face loc pentru teme din saptamana 3

2019-12-13 07:56 UTC, closed without merging